### ISSUE TITLE
Allow running arbitrary commands from the compiled binary.

### ISSUE THREAD

**Issue by ghuls** [NilsIrl/dockerc#29]
Allow running other programs/scripts from the compiled binary instead of only the entrypoint.

As my original docker image inherited from a python image, the entrypoint was still set to python.
But in practice the entrypoint command was never meant to be used (as there are multiple installed
python scripts that are supposed to be run)

```bash
./test python_script1
./test python_script2
```

Similar to
```bash
docker run test:test python_script1
```

**Comment by NilsIrl** [comment]
Arguments are automatically forwarded. So if the entrypoint is set to `./test` then `./bin python_script1` should work.

**Comment by NilsIrl** [comment]
I believe this feature already works so I will close this issue for now.
