### ISSUE TITLE
Problems reading /etc/resolv.conf

### ISSUE THREAD

**Issue by ghuls** [NilsIrl/dockerc#33]
```
$ ./dockerc -i docker://bash:latest -o bash

$ ./bash
unknown argument ignored: lazytime
thread 454460 panic: failed to run container (status/errno: 2) (-1): open `/tmp/dockerc-LOl55b/mount/rootfs/etc/resolv.conf`

Unwind error at address `exe:0x1075145` (error.InvalidDebugInfo), trace may be incomplete

Aborted
```

Apptainer (and probably Docker too) bind mount the host /etc/resolv.conf and /etc/hosts in the default case.
https://github.com/search?q=repo%3Aapptainer%2Fapptainer%20etc%2Fresolv.conf&type=code

**Comment by NilsIrl** [comment]
a workaround for now is to run dockerc as root. the produced binary can then be run as a normal user without issues. I believe this is the same underlying issue as https://github.com/NilsIrl/dockerc/issues/32

**Comment by ghuls** [comment]
Likely. I saw #32, and tried it but it didn't work as I didn't create the image with root rights, but tried to run an already generated image with root.

This works indeed:
```
$ sudo ./dockerc -i docker://bash:latest -o bash
$ ./bash
unknown argument ignored: lazytime
bash-5.2#
```

**Comment by NilsIrl** [comment]
Fixed in https://github.com/NilsIrl/dockerc/commit/598df9fd2e2b29a4fb6b0075f7f696a47193c482
