### ISSUE TITLE
cant run builded binary from dockerc

### ISSUE THREAD

**Issue by Shaverdoff** [NilsIrl/dockerc#35]
Build binary by
dockerc_x86-64 --image docker://mikolatero/vlmcsd:latest --output kms
Getting image source signatures
Copying blob 45b1e6f1031a done   |
Copying blob 8b148e62820f done   |
Copying blob c865bde0d82e done   |
Copying blob 213ec9aee27d done   |
Copying config 6a073888d7 done   |
Writing manifest to image destination
Parallel mksquashfs: Using 12 processors
Creating 4.0 filesystem on kms, block size 131072.
[=======================================================================================================|] 887/887 100%

Exportable Squashfs 4.0 filesystem, zstd compressed, data block size 131072
        compressed data, compressed metadata, compressed fragments,
        no xattrs, compressed ids
        duplicates are removed
Filesystem size 2832.20 Kbytes (2.77 Mbytes)
        40.13% of uncompressed filesystem size (7057.38 Kbytes)
Inode table size 9556 bytes (9.33 Kbytes)
        19.18% of uncompressed inode table size (49813 bytes)
Directory table size 16408 bytes (16.02 Kbytes)
        53.47% of uncompressed directory table size (30687 bytes)
Number of duplicate files found 8
Number of inodes 1326
Number of files 853
Number of fragments 16
Number of symbolic links 332
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 141
Number of hard-links 435
Number of ids (unique uids + gids) 1
Number of uids 1
        user (1000)
Number of gids 1
        user (1000)
but cant run it 

 ./kms
unknown argument ignored: lazytime
thread 1984 panic: failed to run container (status/errno: 2) (-1): open `/tmp/dockerc-Fspx5P/mount/rootfs/etc/resolv.conf`

Unwind error at address `exe:0x1075145` (error.InvalidDebugInfo), trace may be incomplete

Aborted

**Comment by NilsIrl** [comment]
This should be fixed in the latest release. Otherwise a workaround is to run dockerc as root. (then you can run the generated binary as anything).
